[theme]
base = "dark"
primaryColor = "#fbbf24"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "monospace"
rapidapi_key = "3e4d9b6a6b1cf501e2db4a493291f9f5"
